name: 8ktoplasm
description: |
  Online Media Center using Plex, torrent and Amazon Cloud Drive
version: 0.0.1
category: Entertainment
maintainer: Grégoire Fournel <g@tfs.im>
projectURL: https://github.com/8ktoplasm